channels:
  # Needed for appveyor
  sources:
    - ramonaoptics
    - conda-forge
    - defaults
  # Needed for readme generation
  targets:
  - [ramonaoptics, main]

# Needed for ci_support
channel_sources:
- ramonaoptics,conda-forge,defaults

# Needed for ci_support
channel_targets:
- ramonaoptics main

travis:
  secure:
    BINSTAR_TOKEN: gDJ/iOeHr5nHQwyUguo8gHSI64wJTfdaGRr/HmpKPROOcnK9UxfIAmhShPCWbvf1QK9xmvjE4U0n96XHR+wfvBh5alQc2z5DU7tDV8iLzoS+YPhT9jtnQYS0BYXZ0CwUJFXWHRW9ZchMcM0osYAoyWfiwcQH9GbJ3byVs4OVAMFZDBPifCgTslXl3kUmoL2LBv8Jksm0Z5W8NYEVKep5RdYQhBsqyosnE6m3YRR0iJVs5tiYd60UmNmV+WTgL6AIoPS3BPOmvAqS3AI7VWJ/uEjczoENIo8WatA46w8MjBEuLzIdmXQQZxs7EFS3wp1olwFQcFhbO33ZYEMj/Uxf+gyTvR3P5eu1AfygQCi8GgR63opS7odWiF1NzrgYNB0FQ/cncMMEtw7S84YLMmoHf72gigQdtBZxHbSTOoLHGn10qbliYaCadTTkr4AOenQtKW7JBpMA1w2cVp23bUciSLaIHSzaEPoS/U03arYpn6zcUm/vVML2D08x3T95VuUpcebx3e727ReC1+vKPlURIxE0Qp/MC8/tDXGBCwJ5sqUEr8LKomll+Rr807m1rXsg/rVAzfXshJwMlW8RI3j3DqHhTRJ/JBF5MBLVsV0u0Ik3ug6PxbSlCpRw0cFmgU4eVNupnTDKdi2k7FcRu3mi0flBMkBJ3H4X0LyLRrmLlBU=
appveyor:
  secure:
    BINSTAR_TOKEN: a8JN3c8s+67YV0kXG3aTQroHnYbyyZ9QNDK2cc/xJTFHzBnpTnu1jdOdFTb/Epek
