{% set version = "3.2.1" %}

package:
  name: glfw
  version: {{ version }}

source:
  url: https://github.com/glfw/glfw/archive/{{ version }}.tar.gz
  fn: glfw-{{ version}}.tar.gz
  sha256: e10f0de1384d75e6fc210c53e91843f6110d6c4f3afbfb588130713c2f9d8fe8

build:
  number: 0

requirements:
  build:
    # if your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake

#test:
  #imports:
    #- simplejson
    #- simplejson.tests

about:
  home: https://www.glfw.org/
  license: Zlib
  license_file: LICENSE.md
  summary: 'Open Source, multi-platform library for OpenGL, OpenGL ES and Vulkan application development.'

  # The remaining entries in this section are optional, but recommended
  description: |
    GLFW is an Open Source, multi-platform library for OpenGL, OpenGL ES and
    Vulkan application development. It provides a simple,
    platform-independent API for creating windows, contexts and surfaces,
    reading input, handling events, etc.

    GLFW natively supports Windows, macOS and Linux and other Unix-like
    systems.  An experimental implementation for the Wayland protocol is
    available but not yet officially supported.


extra:
  recipe-maintainers:
    - hmaarrfk

